INSERT INTO PLANO_DE_CONTAS (TIPO, DESCRICAO)
                     VALUES ('Receita', 'RECEITAS');
INSERT INTO PLANO_DE_CONTAS (TIPO, DESCRICAO)
                     VALUES ('Despesa', 'DESPESAS OPERACIONAIS');
INSERT INTO PLANO_DE_CONTAS (TIPO, DESCRICAO)
                     VALUES ('Despesa', 'DESPESAS ADMIN PESSOAL');
INSERT INTO PLANO_DE_CONTAS (TIPO, DESCRICAO)
                     VALUES ('Despesa', 'DESPESAS FINANCEIRAS');
INSERT INTO PLANO_DE_CONTAS (TIPO, DESCRICAO)
                     VALUES ('Despesa', 'DEPARTAMENTO PESSOAL');
INSERT INTO PLANO_DE_CONTAS (TIPO, DESCRICAO)
                     VALUES ('Despesa', 'DESPESAS ADMINISTRATIVAS');
INSERT INTO PLANO_DE_CONTAS (TIPO, DESCRICAO)
                     VALUES ('Receita', 'RECEITAS');
INSERT INTO PLANO_DE_CONTAS (TIPO, DESCRICAO)
                     VALUES ('Despesa', 'SERVICOS PUBLICOS');
INSERT INTO PLANO_DE_CONTAS (TIPO, DESCRICAO)
                     VALUES ('Despesa', 'TRANSPORTES');
INSERT INTO PLANO_DE_CONTAS (TIPO, DESCRICAO)
                     VALUES ('Despesa', 'DESPESAS PREDIAIS');
INSERT INTO PLANO_DE_CONTAS (TIPO, DESCRICAO)
                     VALUES ('Despesa', 'INFORMATICA');
INSERT INTO PLANO_DE_CONTAS (TIPO, DESCRICAO)
                     VALUES ('Despesa', 'ESCRITORIO');
INSERT INTO PLANO_DE_CONTAS (TIPO, DESCRICAO)
                     VALUES ('Despesa', 'UNIFORMES');
INSERT INTO PLANO_DE_CONTAS (TIPO, DESCRICAO)
                     VALUES ('Despesa', 'EMBALAGENS');
INSERT INTO PLANO_DE_CONTAS (TIPO, DESCRICAO)
                     VALUES ('Despesa', 'EQUIPAMENTOS');
INSERT INTO PLANO_DE_CONTAS (TIPO, DESCRICAO)
                     VALUES ('Despesa', 'PRESIDENTE');
INSERT INTO PLANO_DE_CONTAS (TIPO, DESCRICAO)
                     VALUES ('Despesa', 'DIRETORES');
INSERT INTO PLANO_DE_CONTAS (TIPO, DESCRICAO)
                     VALUES ('Despesa', 'IMPOSTOS');
INSERT INTO PLANO_DE_CONTAS (TIPO, DESCRICAO)
                     VALUES ('Despesa', 'BANCOS');
INSERT INTO PLANO_DE_CONTAS (TIPO, DESCRICAO)
                     VALUES ('Despesa', 'CARTAO DE CREDITO');
INSERT INTO PLANO_DE_CONTAS (TIPO, DESCRICAO)
                     VALUES ('Despesa', 'TICKET');
INSERT INTO PLANO_DE_CONTAS (TIPO, DESCRICAO)
                     VALUES ('Despesa', 'MARKETING  PROPAGANDA');
INSERT INTO PLANO_DE_CONTAS (TIPO, DESCRICAO)
                     VALUES ('Despesa', 'MANUTENCAO DE FUNCIONARIOS');
INSERT INTO PLANO_DE_CONTAS (TIPO, DESCRICAO)
                     VALUES ('Despesa', 'MANUTENCAO EMPRESA');
INSERT INTO PLANO_DE_CONTAS (TIPO, DESCRICAO)
                     VALUES ('Despesa', 'FORNECEDORES');
INSERT INTO PLANO_DE_CONTAS (TIPO, DESCRICAO)
                     VALUES ('Despesa', 'AGUA');
INSERT INTO PLANO_DE_CONTAS (TIPO, DESCRICAO)
                     VALUES ('Despesa', 'ENERGIA ELETRICA');
INSERT INTO PLANO_DE_CONTAS (TIPO, DESCRICAO)
                     VALUES ('Despesa', 'GAS');
INSERT INTO PLANO_DE_CONTAS (TIPO, DESCRICAO)
                     VALUES ('Despesa', 'TELEFONIA FIXA');
INSERT INTO PLANO_DE_CONTAS (TIPO, DESCRICAO)
                     VALUES ('Despesa', 'TELEFONIA MOVEL');
INSERT INTO PLANO_DE_CONTAS (TIPO, DESCRICAO)
                     VALUES ('Despesa', 'BOMBEIROS');
INSERT INTO PLANO_DE_CONTAS (TIPO, DESCRICAO)
                     VALUES ('Despesa', 'CARTORIOS ASSINATURAS');
INSERT INTO PLANO_DE_CONTAS (TIPO, DESCRICAO)
                     VALUES ('Despesa', 'TAXAS DIVERSAS');
INSERT INTO PLANO_DE_CONTAS (TIPO, DESCRICAO)
                     VALUES ('Despesa', 'CORREIO');
INSERT INTO PLANO_DE_CONTAS (TIPO, DESCRICAO)
                     VALUES ('Despesa', 'GASOLINA');
INSERT INTO PLANO_DE_CONTAS (TIPO, DESCRICAO)
                     VALUES ('Despesa', 'ALCOOL');
INSERT INTO PLANO_DE_CONTAS (TIPO, DESCRICAO)
                     VALUES ('Despesa', 'LUBRIFICANTES E SIMILARES');
INSERT INTO PLANO_DE_CONTAS (TIPO, DESCRICAO)
                     VALUES ('Despesa', 'OLEO DIESEL');
INSERT INTO PLANO_DE_CONTAS (TIPO, DESCRICAO)
                     VALUES ('Despesa', 'ENTREGA');
INSERT INTO PLANO_DE_CONTAS (TIPO, DESCRICAO)
                     VALUES ('Despesa', 'MANUTENCAO');
INSERT INTO PLANO_DE_CONTAS (TIPO, DESCRICAO)
                     VALUES ('Despesa', 'SEGUROS');
INSERT INTO PLANO_DE_CONTAS (TIPO, DESCRICAO)
                     VALUES ('Despesa', 'PEDAGIO');
INSERT INTO PLANO_DE_CONTAS (TIPO, DESCRICAO)
                     VALUES ('Despesa', 'BALSA');
INSERT INTO PLANO_DE_CONTAS (TIPO, DESCRICAO)
                     VALUES ('Despesa', 'FINANCIAMENTOS');
INSERT INTO PLANO_DE_CONTAS (TIPO, DESCRICAO)
                     VALUES ('Despesa', 'AQUISICAO DE VEICULOS');
INSERT INTO PLANO_DE_CONTAS (TIPO, DESCRICAO)
                     VALUES ('Despesa', 'FRETE');
INSERT INTO PLANO_DE_CONTAS (TIPO, DESCRICAO)
                     VALUES ('Despesa', 'IPVA');
INSERT INTO PLANO_DE_CONTAS (TIPO, DESCRICAO)
                     VALUES ('Despesa', 'MULTAS');
INSERT INTO PLANO_DE_CONTAS (TIPO, DESCRICAO)
                     VALUES ('Despesa', 'OFICINA E REVISAO');
INSERT INTO PLANO_DE_CONTAS (TIPO, DESCRICAO)
                     VALUES ('Despesa', 'PASSAGENS');
INSERT INTO PLANO_DE_CONTAS (TIPO, DESCRICAO)
                     VALUES ('Despesa', 'VALE TRANSPORTE');
INSERT INTO PLANO_DE_CONTAS (TIPO, DESCRICAO)
                     VALUES ('Despesa', 'LICENCIAMENTO');
INSERT INTO PLANO_DE_CONTAS (TIPO, DESCRICAO)
                     VALUES ('Despesa', 'PECAS');
INSERT INTO PLANO_DE_CONTAS (TIPO, DESCRICAO)
                     VALUES ('Despesa', 'LAVAGEM E LIMPEZA');
INSERT INTO PLANO_DE_CONTAS (TIPO, DESCRICAO)
                     VALUES ('Despesa', 'PNEUS');
INSERT INTO PLANO_DE_CONTAS (TIPO, DESCRICAO)
                     VALUES ('Despesa', 'ACESSORIOS');
INSERT INTO PLANO_DE_CONTAS (TIPO, DESCRICAO)
                     VALUES ('Despesa', 'CNH  HABILITACAO');
INSERT INTO PLANO_DE_CONTAS (TIPO, DESCRICAO)
                     VALUES ('Despesa', 'ALUGUEL');
INSERT INTO PLANO_DE_CONTAS (TIPO, DESCRICAO)
                     VALUES ('Despesa', 'ALARMES');
INSERT INTO PLANO_DE_CONTAS (TIPO, DESCRICAO)
                     VALUES ('Despesa', 'MANUTENCAO');
INSERT INTO PLANO_DE_CONTAS (TIPO, DESCRICAO)
                     VALUES ('Despesa', 'MONITORAMENTO E SEGURANcA');
INSERT INTO PLANO_DE_CONTAS (TIPO, DESCRICAO)
                     VALUES ('Despesa', 'SEGUROS');
INSERT INTO PLANO_DE_CONTAS (TIPO, DESCRICAO)
                     VALUES ('Despesa', 'MATERIAL DE LIMPEZA');
INSERT INTO PLANO_DE_CONTAS (TIPO, DESCRICAO)
                     VALUES ('Despesa', 'DEDETIZACAO  DESRATIZACAO');
INSERT INTO PLANO_DE_CONTAS (TIPO, DESCRICAO)
                     VALUES ('Despesa', 'ALUGUEL DE MAQUINAS');
INSERT INTO PLANO_DE_CONTAS (TIPO, DESCRICAO)
                     VALUES ('Despesa', 'ALUGUEL DE PROGRAMAS');
INSERT INTO PLANO_DE_CONTAS (TIPO, DESCRICAO)
                     VALUES ('Despesa', 'CONTRATO DE MANUTENCAO');
INSERT INTO PLANO_DE_CONTAS (TIPO, DESCRICAO)
                     VALUES ('Despesa', 'MANUTENCAO AVULSA');
INSERT INTO PLANO_DE_CONTAS (TIPO, DESCRICAO)
                     VALUES ('Despesa', 'FORMULARIOS');
INSERT INTO PLANO_DE_CONTAS (TIPO, DESCRICAO)
                     VALUES ('Despesa', 'SUPRIMENTOS');
INSERT INTO PLANO_DE_CONTAS (TIPO, DESCRICAO)
                     VALUES ('Despesa', 'SUPRIMENTOS PDV');
INSERT INTO PLANO_DE_CONTAS (TIPO, DESCRICAO)
                     VALUES ('Despesa', 'EQUIPAMENTOS');
INSERT INTO PLANO_DE_CONTAS (TIPO, DESCRICAO)
                     VALUES ('Despesa', 'CURSOS E TREINAMENTOS');
INSERT INTO PLANO_DE_CONTAS (TIPO, DESCRICAO)
                     VALUES ('Despesa', 'ACESSORIOS');
INSERT INTO PLANO_DE_CONTAS (TIPO, DESCRICAO)
                     VALUES ('Despesa', 'EQUIPAMENTO');
INSERT INTO PLANO_DE_CONTAS (TIPO, DESCRICAO)
                     VALUES ('Despesa', 'MATERIAL PERMANENTE');
INSERT INTO PLANO_DE_CONTAS (TIPO, DESCRICAO)
                     VALUES ('Despesa', 'XEROX');
INSERT INTO PLANO_DE_CONTAS (TIPO, DESCRICAO)
                     VALUES ('Despesa', 'MANUTENCAO DE ESCRITORIO');
INSERT INTO PLANO_DE_CONTAS (TIPO, DESCRICAO)
                     VALUES ('Despesa', 'FRENTE DE CAIXA');
INSERT INTO PLANO_DE_CONTAS (TIPO, DESCRICAO)
                     VALUES ('Despesa', 'ESCRITORIO');
INSERT INTO PLANO_DE_CONTAS (TIPO, DESCRICAO)
                     VALUES ('Despesa', 'SERVICO');
INSERT INTO PLANO_DE_CONTAS (TIPO, DESCRICAO)
                     VALUES ('Despesa', 'TEMPORARIO');
INSERT INTO PLANO_DE_CONTAS (TIPO, DESCRICAO)
                     VALUES ('Despesa', 'SACOS  SACOLAS DE PAPEL');
INSERT INTO PLANO_DE_CONTAS (TIPO, DESCRICAO)
                     VALUES ('Despesa', 'SACOS  SACOLAS PLASTICOS');
INSERT INTO PLANO_DE_CONTAS (TIPO, DESCRICAO)
                     VALUES ('Despesa', 'BANDEJAS  PRATOS');
INSERT INTO PLANO_DE_CONTAS (TIPO, DESCRICAO)
                     VALUES ('Despesa', 'POTES, TACAS, COPOS');
INSERT INTO PLANO_DE_CONTAS (TIPO, DESCRICAO)
                     VALUES ('Despesa', 'MATERIAL DIVERSO');
INSERT INTO PLANO_DE_CONTAS (TIPO, DESCRICAO)
                     VALUES ('Despesa', 'AQUISICAO DE EQUIPAMENTO');
INSERT INTO PLANO_DE_CONTAS (TIPO, DESCRICAO)
                     VALUES ('Despesa', 'MATERIAIS');
INSERT INTO PLANO_DE_CONTAS (TIPO, DESCRICAO)
                     VALUES ('Despesa', 'MANUTENCAO');
INSERT INTO PLANO_DE_CONTAS (TIPO, DESCRICAO)
                     VALUES ('Despesa', 'PROLABORE');
INSERT INTO PLANO_DE_CONTAS (TIPO, DESCRICAO)
                     VALUES ('Despesa', 'PROLABORE');
INSERT INTO PLANO_DE_CONTAS (TIPO, DESCRICAO)
                     VALUES ('Despesa', 'COFINS');
INSERT INTO PLANO_DE_CONTAS (TIPO, DESCRICAO)
                     VALUES ('Despesa', 'CONTRIBUICAO SINDICAL');
INSERT INTO PLANO_DE_CONTAS (TIPO, DESCRICAO)
                     VALUES ('Despesa', 'ICMS');
INSERT INTO PLANO_DE_CONTAS (TIPO, DESCRICAO)
                     VALUES ('Despesa', 'IPTU');
INSERT INTO PLANO_DE_CONTAS (TIPO, DESCRICAO)
                     VALUES ('Despesa', 'IR');
INSERT INTO PLANO_DE_CONTAS (TIPO, DESCRICAO)
                     VALUES ('Despesa', 'PIS PASEP');
INSERT INTO PLANO_DE_CONTAS (TIPO, DESCRICAO)
                     VALUES ('Despesa', 'GFIP');
INSERT INTO PLANO_DE_CONTAS (TIPO, DESCRICAO)
                     VALUES ('Despesa', 'IRPJ');
INSERT INTO PLANO_DE_CONTAS (TIPO, DESCRICAO)
                     VALUES ('Despesa', 'LICENCA SANITARIA');
INSERT INTO PLANO_DE_CONTAS (TIPO, DESCRICAO)
                     VALUES ('Despesa', 'ISSQN');
INSERT INTO PLANO_DE_CONTAS (TIPO, DESCRICAO)
                     VALUES ('Despesa', 'DARF SIMPLES');
INSERT INTO PLANO_DE_CONTAS (TIPO, DESCRICAO)
                     VALUES ('Despesa', 'GPS');
INSERT INTO PLANO_DE_CONTAS (TIPO, DESCRICAO)
                     VALUES ('Despesa', 'IRRF');
INSERT INTO PLANO_DE_CONTAS (TIPO, DESCRICAO)
                     VALUES ('Despesa', 'JUROS');
INSERT INTO PLANO_DE_CONTAS (TIPO, DESCRICAO)
                     VALUES ('Despesa', 'TARIFAS');
INSERT INTO PLANO_DE_CONTAS (TIPO, DESCRICAO)
                     VALUES ('Despesa', 'TAXAS');
INSERT INTO PLANO_DE_CONTAS (TIPO, DESCRICAO)
                     VALUES ('Despesa', 'CPMF');
INSERT INTO PLANO_DE_CONTAS (TIPO, DESCRICAO)
                     VALUES ('Despesa', 'JUROS DESC CHEQUE');
INSERT INTO PLANO_DE_CONTAS (TIPO, DESCRICAO)
                     VALUES ('Despesa', 'TALAO DE CHEQUES');
INSERT INTO PLANO_DE_CONTAS (TIPO, DESCRICAO)
                     VALUES ('Despesa', 'TRANSFERENCIA');
INSERT INTO PLANO_DE_CONTAS (TIPO, DESCRICAO)
                     VALUES ('Despesa', 'IOF');
INSERT INTO PLANO_DE_CONTAS (TIPO, DESCRICAO)
                     VALUES ('Despesa', 'JUROS');
INSERT INTO PLANO_DE_CONTAS (TIPO, DESCRICAO)
                     VALUES ('Despesa', 'TAXAS');
INSERT INTO PLANO_DE_CONTAS (TIPO, DESCRICAO)
                     VALUES ('Despesa', 'CPMF');
INSERT INTO PLANO_DE_CONTAS (TIPO, DESCRICAO)
                     VALUES ('Despesa', 'IOF');
INSERT INTO PLANO_DE_CONTAS (TIPO, DESCRICAO)
                     VALUES ('Despesa', 'CPMF');
INSERT INTO PLANO_DE_CONTAS (TIPO, DESCRICAO)
                     VALUES ('Despesa', 'JUROS');
INSERT INTO PLANO_DE_CONTAS (TIPO, DESCRICAO)
                     VALUES ('Despesa', 'TAXAS DE ADIANTAMENTO');
INSERT INTO PLANO_DE_CONTAS (TIPO, DESCRICAO)
                     VALUES ('Despesa', 'IOF');
INSERT INTO PLANO_DE_CONTAS (TIPO, DESCRICAO)
                     VALUES ('Despesa', 'CARRO DE SOM');
INSERT INTO PLANO_DE_CONTAS (TIPO, DESCRICAO)
                     VALUES ('Despesa', 'CRACHAS, CARTOES');
INSERT INTO PLANO_DE_CONTAS (TIPO, DESCRICAO)
                     VALUES ('Despesa', 'CURSOS TREINAMENTO');
INSERT INTO PLANO_DE_CONTAS (TIPO, DESCRICAO)
                     VALUES ('Despesa', 'DOACOES, PATROCINIOS');
INSERT INTO PLANO_DE_CONTAS (TIPO, DESCRICAO)
                     VALUES ('Despesa', 'IMPRESSOS DIVERSOS');
INSERT INTO PLANO_DE_CONTAS (TIPO, DESCRICAO)
                     VALUES ('Despesa', 'PLACAS E LUMINOSOS');
INSERT INTO PLANO_DE_CONTAS (TIPO, DESCRICAO)
                     VALUES ('Despesa', 'COMUNICACAO VISUAL');
INSERT INTO PLANO_DE_CONTAS (TIPO, DESCRICAO)
                     VALUES ('Despesa', 'REFEICOES');
INSERT INTO PLANO_DE_CONTAS (TIPO, DESCRICAO)
                     VALUES ('Despesa', 'RADIO  TV');
INSERT INTO PLANO_DE_CONTAS (TIPO, DESCRICAO)
                     VALUES ('Despesa', 'SALARIO DE FUNCIONARIOS');
INSERT INTO PLANO_DE_CONTAS (TIPO, DESCRICAO)
                     VALUES ('Despesa', '13 SALARIO');
INSERT INTO PLANO_DE_CONTAS (TIPO, DESCRICAO)
                     VALUES ('Despesa', 'SALARIO FERIAS');
INSERT INTO PLANO_DE_CONTAS (TIPO, DESCRICAO)
                     VALUES ('Despesa', 'HORAS EXTRAS');
INSERT INTO PLANO_DE_CONTAS (TIPO, DESCRICAO)
                     VALUES ('Despesa', 'RESCISAO DE CONTRATO');
INSERT INTO PLANO_DE_CONTAS (TIPO, DESCRICAO)
                     VALUES ('Despesa', 'ADIANTAMENTO  VALE');
INSERT INTO PLANO_DE_CONTAS (TIPO, DESCRICAO)
                     VALUES ('Despesa', 'EXAMES MEDICOS');
INSERT INTO PLANO_DE_CONTAS (TIPO, DESCRICAO)
                     VALUES ('Despesa', 'REFEICOES, LANCHES');
INSERT INTO PLANO_DE_CONTAS (TIPO, DESCRICAO)
                     VALUES ('Despesa', 'HOSPEDAGEM');
INSERT INTO PLANO_DE_CONTAS (TIPO, DESCRICAO)
                     VALUES ('Despesa', 'CRECHE');
INSERT INTO PLANO_DE_CONTAS (TIPO, DESCRICAO)
                     VALUES ('Despesa', 'INSTRUCAO ESCOLAR');
INSERT INTO PLANO_DE_CONTAS (TIPO, DESCRICAO)
                     VALUES ('Despesa', 'DOACOES');
INSERT INTO PLANO_DE_CONTAS (TIPO, DESCRICAO)
                     VALUES ('Despesa', 'PREMIACOES');
INSERT INTO PLANO_DE_CONTAS (TIPO, DESCRICAO)
                     VALUES ('Despesa', 'COMISSOES');
INSERT INTO PLANO_DE_CONTAS (TIPO, DESCRICAO)
                     VALUES ('Despesa', 'HONORARIOS ADVOCACIA');
INSERT INTO PLANO_DE_CONTAS (TIPO, DESCRICAO)
                     VALUES ('Despesa', 'CONSULTORIA');
INSERT INTO PLANO_DE_CONTAS (TIPO, DESCRICAO)
                     VALUES ('Despesa', 'HONORARIOS CONTABEIS');
INSERT INTO PLANO_DE_CONTAS (TIPO, DESCRICAO)
                     VALUES ('Despesa', 'PGTO FORNECEDORES');
INSERT INTO PLANO_DE_CONTAS (TIPO, DESCRICAO)
                     VALUES ('Receita', 'ADIANTAMENTO DE CLIENTE');
INSERT INTO PLANO_DE_CONTAS (TIPO, DESCRICAO)
                     VALUES ('Receita', 'DESCONTO  BONIFICACAO');
INSERT INTO PLANO_DE_CONTAS (TIPO, DESCRICAO)
                     VALUES ('Receita', 'JUROS RECEBIDO');
INSERT INTO PLANO_DE_CONTAS (TIPO, DESCRICAO)
                     VALUES ('Receita', 'HAVERES');
INSERT INTO PLANO_DE_CONTAS (TIPO, DESCRICAO)
                     VALUES ('Receita', 'RECUPERACAO DE DESPESA');
INSERT INTO PLANO_DE_CONTAS (TIPO, DESCRICAO)
                     VALUES ('Receita', 'SALDO ANTERIOR');
INSERT INTO PLANO_DE_CONTAS (TIPO, DESCRICAO)
                     VALUES ('Receita', 'TRANSFERENCIA BANCARIA');
INSERT INTO PLANO_DE_CONTAS (TIPO, DESCRICAO)
                     VALUES ('Receita', 'VENDAS A VISTA');
INSERT INTO PLANO_DE_CONTAS (TIPO, DESCRICAO)
                     VALUES ('Receita', 'VENDAS A PRAZO');
INSERT INTO PLANO_DE_CONTAS (TIPO, DESCRICAO)
                     VALUES ('Receita', 'OS A VISTA');
INSERT INTO PLANO_DE_CONTAS (TIPO, DESCRICAO)
                     VALUES ('Receita', 'OS A PRAZO');
INSERT INTO PLANO_DE_CONTAS (TIPO, DESCRICAO)
                     VALUES ('Receita', 'RECEBIMENTO CREDIARIO');
INSERT INTO PLANO_DE_CONTAS (TIPO, DESCRICAO)
                     VALUES ('Receita', 'VENDA DINHEIRO');
INSERT INTO PLANO_DE_CONTAS (TIPO, DESCRICAO)
                     VALUES ('Receita', 'VENDA CHEQUE VISTA');
INSERT INTO PLANO_DE_CONTAS (TIPO, DESCRICAO)
                     VALUES ('Receita', 'VENDA CHEQUE PRAZO');
INSERT INTO PLANO_DE_CONTAS (TIPO, DESCRICAO)
                     VALUES ('Receita', 'VENDA DUPLICATA');
INSERT INTO PLANO_DE_CONTAS (TIPO, DESCRICAO)
                     VALUES ('Receita', 'VENDA CARTAO');
INSERT INTO PLANO_DE_CONTAS (TIPO, DESCRICAO)
                     VALUES ('Receita', 'OS DINHEIRO');
INSERT INTO PLANO_DE_CONTAS (TIPO, DESCRICAO)
                     VALUES ('Receita', 'OS CHEQUE VISTA');
INSERT INTO PLANO_DE_CONTAS (TIPO, DESCRICAO)
                     VALUES ('Receita', 'OS CHEQUE PRAZO');
INSERT INTO PLANO_DE_CONTAS (TIPO, DESCRICAO)
                     VALUES ('Receita', 'OS DUPLICATA');
INSERT INTO PLANO_DE_CONTAS (TIPO, DESCRICAO)
                     VALUES ('Receita', 'OS CARTAO');
INSERT INTO PLANO_DE_CONTAS (TIPO, DESCRICAO)
                     VALUES ('Receita', 'RECEBIMENTO DINHEIRO');
INSERT INTO PLANO_DE_CONTAS (TIPO, DESCRICAO)
                     VALUES ('Receita', 'RECEBIMENTO CHEQUE VISTA');
INSERT INTO PLANO_DE_CONTAS (TIPO, DESCRICAO)
                     VALUES ('Receita', 'RECEBIMENTO CHEQUE PRAZO');
INSERT INTO PLANO_DE_CONTAS (TIPO, DESCRICAO)
                     VALUES ('Receita', 'RECEBIMENTO DUPLICATA');
INSERT INTO PLANO_DE_CONTAS (TIPO, DESCRICAO)
                     VALUES ('Receita', 'RECEBIMENTO CARTAO');
INSERT INTO PLANO_DE_CONTAS (TIPO, DESCRICAO)
                     VALUES ('Despesa', 'MATERIA PRIMA');
INSERT INTO PLANO_DE_CONTAS (TIPO, DESCRICAO)
                     VALUES ('Despesa', 'MANUTENCAO PREDIAL');
INSERT INTO PLANO_DE_CONTAS (TIPO, DESCRICAO)
                     VALUES ('Receita', 'VENDAS PDV A VISTA');
INSERT INTO PLANO_DE_CONTAS (TIPO, DESCRICAO)
                     VALUES ('Receita', 'VENDAS PDV CHEQUE');
INSERT INTO PLANO_DE_CONTAS (TIPO, DESCRICAO)
                     VALUES ('Receita', 'VENDAS PDV CARTAO');
INSERT INTO PLANO_DE_CONTAS (TIPO, DESCRICAO)
                     VALUES ('Receita', 'VENDAS PDV CREDIARIO');
INSERT INTO PLANO_DE_CONTAS (TIPO, DESCRICAO)
                     VALUES ('Receita', 'VENDAS PDV CONVENIO');

COMMIT WORK;
